#include "models/starvla/oft_image_preprocess.h"

#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>

namespace {

void require(bool condition, const char * message) {
    if (!condition) {
        std::cerr << "FAIL: " << message << '\n';
        std::exit(1);
    }
}

uint64_t fnv1a(const std::vector<uint8_t> & values) {
    uint64_t hash = UINT64_C(14695981039346656037);
    for (uint8_t value : values) {
        hash ^= value;
        hash *= UINT64_C(1099511628211);
    }
    return hash;
}

std::vector<uint8_t> test_image(int width, int height, int stride) {
    std::vector<uint8_t> image(static_cast<size_t>(stride) * height, 0xee);
    for (int y = 0; y < height; ++y) {
        for (int x = 0; x < width; ++x) {
            for (int c = 0; c < 3; ++c) {
                image[static_cast<size_t>(y) * stride + x * 3 + c] =
                    static_cast<uint8_t>((x * 37 + y * 61 + c * 83 + x * y * 7) & 0xff);
            }
        }
    }
    return image;
}

} // namespace

int main() {
    using namespace robotcpp::starvla;

    const int width = 7;
    const int height = 5;
    const int stride = width * 3 + 5;
    const std::vector<uint8_t> source = test_image(width, height, stride);
    std::vector<uint8_t> pillow;
    std::vector<uint8_t> torch;
    std::string error;
    require(resize_pillow_bicubic_rgb(source.data(), width, height, stride, 4, 6, pillow, error),
            "Pillow bicubic resize must succeed");
    require(resize_torchvision_bicubic_aa_rgb(source.data(), width, height, stride, 8, 9, torch, error),
            "torchvision bicubic resize must succeed");
    require(pillow.size() == 4 * 6 * 3, "Pillow resize shape must be exact");
    require(torch.size() == 8 * 9 * 3, "torchvision resize shape must be exact");

    // Byte-for-byte references: Pillow 7.0.0 and torchvision's uint8 bicubic-AA path.
    require(fnv1a(pillow) == UINT64_C(13888783175115780895),
            "Pillow bicubic resize must match the reference bytes");
    require(fnv1a(torch) == UINT64_C(14284510537394890340),
            "torchvision bicubic-AA resize must match the reference bytes");

    std::vector<uint8_t> processed;
    require(preprocess_oft_rgb(source.data(), width, height, 3, stride, 4, 6, 8, 9,
                               processed, error),
            "two-stage OFT preprocessing must succeed");
    require(processed.size() == 8 * 9 * 3, "two-stage OFT image shape must be exact");
    require(fnv1a(processed) == UINT64_C(11011422699469149164),
            "two-stage OFT preprocessing must match the reference bytes");

    int smart_width = 0;
    int smart_height = 0;
    require(qwen3vl_smart_resize_dimensions(640, 488, 32, 65536, 16777216,
                                            smart_width, smart_height, error),
            "Qwen3-VL smart resize dimensions must succeed");
    require(smart_width == 640 && smart_height == 480,
            "640x488 must map to the official 640x480 grid");
    require(qwen3vl_smart_resize_dimensions(640, 400, 32, 65536, 16777216,
                                            smart_width, smart_height, error),
            "Qwen3-VL ties-to-even smart resize must succeed");
    require(smart_width == 640 && smart_height == 384,
            "Python ties-to-even rounding must map 400 pixels to 384");

    std::vector<uint8_t> smart;
    int smart_tokens = 0;
    require(preprocess_qwen3vl_rgb(source.data(), width, height, 3, stride, 16, 2,
                                  65536, 16777216, smart, smart_width, smart_height,
                                  smart_tokens, error),
            "Qwen3-VL dynamic preprocessing must succeed");
    require(smart_width == 320 && smart_height == 224 && smart_tokens == 70,
            "Qwen3-VL dynamic preprocessing must report its exact grid and token count");
    require(smart.size() == static_cast<size_t>(smart_width) * smart_height * 3,
            "Qwen3-VL dynamic image shape must be exact");

    const int official_width = 640;
    const int official_height = 488;
    const int official_stride = official_width * 3 + 5;
    const std::vector<uint8_t> official_shape_source =
        test_image(official_width, official_height, official_stride);
    require(preprocess_qwen3vl_rgb(
                official_shape_source.data(), official_width, official_height, 3,
                official_stride, 16, 2, 65536, 16777216, smart, smart_width,
                smart_height, smart_tokens, error),
            "official-shape Qwen3-VL preprocessing must succeed");
    require(smart_width == 640 && smart_height == 480 && smart_tokens == 300,
            "official-shape Qwen3-VL preprocessing must produce a 30x40 merged grid");
    // Reference generated by torchvision 0.21's uint8 bicubic antialias path.
    require(fnv1a(smart) == UINT64_C(11336294493867056015),
            "official-shape Qwen3-VL resize must match torchvision bytes");

    require(preprocess_qwen3vl_rgb(
                official_shape_source.data(), official_width, official_height, 3,
                official_stride, 14, 2, 3136, 12845056, smart, smart_width,
                smart_height, smart_tokens, error),
            "official-shape Qwen2.5-VL preprocessing must succeed");
    require(smart_width == 644 && smart_height == 476 && smart_tokens == 391,
            "Qwen2.5-VL preprocessing must produce its exact 17x23 merged grid");
    // Reference generated by Transformers 4.57 / torchvision 0.21 fast Qwen2-VL
    // image preprocessing on the same uint8 RGB tensor.
    require(fnv1a(smart) == UINT64_C(12050652900109057577),
            "Qwen2.5-VL resize must match torchvision bytes");

    const int bridge_width = 256;
    const int bridge_height = 256;
    const int bridge_stride = bridge_width * 3;
    const std::vector<uint8_t> bridge_source =
        test_image(bridge_width, bridge_height, bridge_stride);
    require(preprocess_qwen3vl_rgb(
                bridge_source.data(), bridge_width, bridge_height, 3,
                bridge_stride, 14, 2, 3136, 12845056, smart, smart_width,
                smart_height, smart_tokens, error),
            "Bridge-size Qwen2.5-VL preprocessing must succeed");
    require(smart_width == 252 && smart_height == 252 && smart_tokens == 81,
            "256x256 Bridge input must map to the official 18x18 patch grid");
    require(smart.size() == static_cast<size_t>(252 * 252 * 3),
            "Bridge-size Qwen2.5-VL preprocessing must return 252x252 RGB");

    const int adapter_width = 224;
    const int adapter_height = 224;
    const int adapter_stride = adapter_width * 3;
    const std::vector<uint8_t> adapter_source =
        test_image(adapter_width, adapter_height, adapter_stride);
    require(preprocess_qwen3vl_rgb(
                adapter_source.data(), adapter_width, adapter_height, 3,
                adapter_stride, 14, 2, 3136, 12845056, smart, smart_width,
                smart_height, smart_tokens, error),
            "SimplerEnv adapter-size Qwen2.5-VL preprocessing must succeed");
    require(smart_width == 224 && smart_height == 224 && smart_tokens == 64,
            "224x224 SimplerEnv input must preserve its official 16x16 patch grid");
    require(smart.size() == static_cast<size_t>(224 * 224 * 3),
            "SimplerEnv adapter-size preprocessing must return 224x224 RGB");

    require(!qwen3vl_smart_resize_dimensions(640, 3, 32, 65536, 16777216,
                                             smart_width, smart_height, error),
            "Qwen3-VL smart resize must reject aspect ratios over 200");

    std::cout << "pillow_fnv=" << fnv1a(pillow) << " torch_fnv=" << fnv1a(torch)
              << " two_stage_fnv=" << fnv1a(processed) << '\n';
    return 0;
}
