name: gguf_converter
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - numpy
      - safetensors
      - huggingface_hub>=0.36.0
      - sentencepiece
      - transformers==4.53.2
      - pillow==12.1.1
      - pyyaml
